import {
  SiteEditorSettings,
  SitePage,
} from "./theme-types";

export const sampleSitePages: SitePage[] = [
  { id: "page-1", type: "home", title: "Home", path: "/", enabled: true },
  { id: "page-2", type: "products", title: "Shop", path: "/shop", enabled: true },
  { id: "page-3", type: "categories", title: "Categories", path: "/categories", enabled: true },
  { id: "page-4", type: "cart", title: "Cart", path: "/cart", enabled: true },
  { id: "page-5", type: "checkout", title: "Checkout", path: "/checkout", enabled: true },
  { id: "page-6", type: "about", title: "About", path: "/about", enabled: true },
  { id: "page-7", type: "contact", title: "Contact", path: "/contact", enabled: true },
  { id: "page-8", type: "faq", title: "FAQ", path: "/faq", enabled: true },
  { id: "page-9", type: "privacy", title: "Privacy Policy", path: "/privacy", enabled: true },
  { id: "page-10", type: "terms", title: "Terms", path: "/terms", enabled: true },
  { id: "page-11", type: "productDetail", title: "Product", path: "/shop/:slug", enabled: true },
  { id: "page-12", type: "notFound", title: "Page Not Found", path: "/404", enabled: true },
];

export const defaultSettings: SiteEditorSettings = {
  siteName: "Maison",
  logoType: "text",
  logoImage: "",
  tagline: "",
  primaryColor: "#1c1917",
  accentColor: "#78716c",
  surfaceColor: "#faf9f6",
  displayFont: "fraunces",
  bodyFont: "inter",
  buttonStyle: "Square",
  navLinks: [
    { id: "nav-1", label: "Shop", path: "/shop" },
    { id: "nav-2", label: "Women", path: "/shop?category=women" },
    { id: "nav-3", label: "Men", path: "/shop?category=men" },
    { id: "nav-4", label: "About", path: "/about" },
  ],
  headerButtons: [],
  pages: sampleSitePages,
  sections: [
    { id: "sec-1", type: "hero" },
    { id: "sec-2", type: "banner" },
    { id: "sec-3", type: "categories" },
    { id: "sec-4", type: "featureProducts" },
    { id: "sec-5", type: "productShowcase" },
    { id: "sec-6", type: "testimonials" },
    { id: "sec-7", type: "features" },
    { id: "sec-8", type: "footer" },
  ],
  announcementItems: [],
  announcementDivider: "✦",
  heroImages: [],
  heroImagesSquare: [],
  selectedEventIds: [],
  categoriesTitle: "The collections.",
  selectedCategoryIds: [],
  featureProductsTitle: "New arrivals.",
  selectedProductIds: [],
  showcaseProductId: "",
  whyTitle: "Why customers trust Maison",
  whyImage: "",
  why1Title: "",
  why1: "",
  why2Title: "",
  why2: "",
  why3Title: "",
  why3: "",
  categoryShowcaseTitle: "Shop by collection",
  categoryShowcaseCategoryIds: [],
  featuresTitle: "Our Commitments",
  feature1Title: "",
  feature1: "",
  feature1IconKind: "icon",
  feature1Icon: "truck",
  feature1Image: "",
  feature2Title: "",
  feature2: "",
  feature2IconKind: "icon",
  feature2Icon: "refresh-cw",
  feature2Image: "",
  feature3Title: "",
  feature3: "",
  feature3IconKind: "icon",
  feature3Icon: "leaf",
  feature3Image: "",
  testimonialsTitle: "",
  testimonials: [],
  ctaTitle: "",
  ctaBody: "",
  ctaButton: "",
  footerDescription: "",
  footerShopLabel: "Shop",
  footerShopLinks: [
    { id: "fs1", label: "Women", path: "/shop?category=women" },
    { id: "fs2", label: "Men", path: "/shop?category=men" },
    { id: "fs3", label: "Bags", path: "/shop?category=bags" },
    { id: "fs4", label: "Accessories", path: "/shop?category=accessories" },
  ],
  footerCompanyLabel: "Company",
  footerCompanyLinks: [
    { id: "fc1", label: "About", path: "/about" },
    { id: "fc2", label: "Contact", path: "/contact" },
    { id: "fc3", label: "FAQ", path: "/faq" },
  ],
};
